/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerGame;

/**
 *
 * @author Jéssica Petersen
 */
public class view extends javax.swing.JFrame {
    
    private ControllerGame controller;
    private boolean ganhou;

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        controller = new ControllerGame();
        atualizaLabels();
    }
    
    private void atualizaLabels(){
        this.textFeedback.setText("<html>"+controller.getFeedback()+"</html>");
        this.textJogador.setText("<html>"+controller.getJogadorAtual()+"</html>");
        this.textVitoriaJogador1.setText("<html>"+controller.getJogo().getVitoriasJogadorUm()+"</html>");
        this.textVitoriaJogador2.setText("<html>"+controller.getJogo().getVitoriasJogadorDois()+"</html>");
        ganhou = this.controller.isGanhou();
    }

    public void resetTabuleiro(){
        String[] linha = {"A", "B", "C"};
        String[] coluna = {"A","B", "C"};
        
        for(String sL: linha){
            for(String sC: coluna){
                atualizaClick(sL+"_"+sC);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        A_A = new javax.swing.JLabel();
        A_B = new javax.swing.JLabel();
        A_C = new javax.swing.JLabel();
        B_A = new javax.swing.JLabel();
        B_B = new javax.swing.JLabel();
        B_C = new javax.swing.JLabel();
        C_A = new javax.swing.JLabel();
        C_B = new javax.swing.JLabel();
        C_C = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textJogador = new javax.swing.JLabel();
        textFeedback = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnNovaPartida = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        textVitoriaJogador1 = new javax.swing.JLabel();
        textVitoriaJogador2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A_A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0.png"))); // NOI18N
        A_A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_AMouseClicked(evt);
            }
        });
        jPanel1.add(A_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 150));

        A_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0.png"))); // NOI18N
        A_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_BMouseClicked(evt);
            }
        });
        jPanel1.add(A_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 240, 150));

        A_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0.png"))); // NOI18N
        A_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_CMouseClicked(evt);
            }
        });
        jPanel1.add(A_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 190, 150));

        B_A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0.png"))); // NOI18N
        B_A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_AMouseClicked(evt);
            }
        });
        jPanel1.add(B_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 190, 220));

        B_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0.png"))); // NOI18N
        B_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_BMouseClicked(evt);
            }
        });
        jPanel1.add(B_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 210, 220));

        B_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0.png"))); // NOI18N
        B_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CMouseClicked(evt);
            }
        });
        jPanel1.add(B_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 190, 220));

        C_A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0.png"))); // NOI18N
        C_A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C_AMouseClicked(evt);
            }
        });
        jPanel1.add(C_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 190, 160));

        C_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0.png"))); // NOI18N
        C_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C_BMouseClicked(evt);
            }
        });
        jPanel1.add(C_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 220, 160));

        C_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/0.png"))); // NOI18N
        C_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C_CMouseClicked(evt);
            }
        });
        jPanel1.add(C_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 190, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quadrado.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 640));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Agora é a vez do Jogador nº");

        textJogador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textJogador.setText("1");

        textFeedback.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textFeedback.setForeground(new java.awt.Color(255, 51, 51));
        textFeedback.setText("jLabel3");
        textFeedback.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Quantidades de vitórias:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Jogador 1:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Jogador 2:");

        btnNovaPartida.setText("Nova Partida");
        btnNovaPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovaPartidaMouseClicked(evt);
            }
        });
        btnNovaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaPartidaActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReiniciarMouseClicked(evt);
            }
        });
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        textVitoriaJogador1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textVitoriaJogador1.setText("1");

        textVitoriaJogador2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textVitoriaJogador2.setText("2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textVitoriaJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textVitoriaJogador2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(btnReiniciar))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnNovaPartida))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textJogador))
                        .addGap(67, 67, 67)
                        .addComponent(textFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textVitoriaJogador1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textVitoriaJogador2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReiniciar)
                            .addComponent(btnNovaPartida))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPartidaActionPerformed
     this.controller = new ControllerGame();
       this.controller.reset();
       atualizaLabels();
       resetTabuleiro();
    }//GEN-LAST:event_btnNovaPartidaActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
       this.controller = new ControllerGame();
       this.controller.newGame();
       atualizaLabels();
       resetTabuleiro();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void A_AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_AMouseClicked
        if(this.controller.pecaClicada("A_A") && !ganhou){
            this.atualizaClick("A_A");
        }
        atualizaLabels();
    }//GEN-LAST:event_A_AMouseClicked

    private void A_BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_BMouseClicked
       if(this.controller.pecaClicada("A_B") && !ganhou){
            this.atualizaClick("A_B");
       }
       atualizaLabels();
    }//GEN-LAST:event_A_BMouseClicked

    private void A_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_CMouseClicked
       if(this.controller.pecaClicada("A_C") && !ganhou){
            this.atualizaClick("A_C");
       }
       atualizaLabels();
    }//GEN-LAST:event_A_CMouseClicked

    private void B_AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_AMouseClicked
       if(this.controller.pecaClicada("B_A") && !ganhou){
            this.atualizaClick("B_A");
       }
       atualizaLabels();
    }//GEN-LAST:event_B_AMouseClicked

    private void C_AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_AMouseClicked
        if(this.controller.pecaClicada("C_A") && !ganhou){
            this.atualizaClick("C_A");
        }
        atualizaLabels();
    }//GEN-LAST:event_C_AMouseClicked

    private void C_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_CMouseClicked
        if(this.controller.pecaClicada("C_C") && !ganhou){
            this.atualizaClick("C_C");
        }
        atualizaLabels();
    }//GEN-LAST:event_C_CMouseClicked

    private void C_BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_BMouseClicked
         if(this.controller.pecaClicada("C_B") && !ganhou){
             this.atualizaClick("C_B");
         }
        atualizaLabels();
    }//GEN-LAST:event_C_BMouseClicked

    private void B_BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_BMouseClicked
        if(this.controller.pecaClicada("B_B") && !ganhou){
            this.atualizaClick("B_B");
        }
        atualizaLabels();
    }//GEN-LAST:event_B_BMouseClicked

    private void B_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CMouseClicked
         if(this.controller.pecaClicada("B_C") && !ganhou){
            this.atualizaClick("B_C");
         }
         atualizaLabels();
    }//GEN-LAST:event_B_CMouseClicked

    private void btnNovaPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaPartidaMouseClicked
       this.controller = new ControllerGame();
       this.controller.reset();
       atualizaLabels();
       resetTabuleiro();
    }//GEN-LAST:event_btnNovaPartidaMouseClicked

    private void btnReiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReiniciarMouseClicked
        this.controller = new ControllerGame();
        this.controller.newGame();
       atualizaLabels();
       resetTabuleiro();
    }//GEN-LAST:event_btnReiniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A_A;
    private javax.swing.JLabel A_B;
    private javax.swing.JLabel A_C;
    private javax.swing.JLabel B_A;
    private javax.swing.JLabel B_B;
    private javax.swing.JLabel B_C;
    private javax.swing.JLabel C_A;
    private javax.swing.JLabel C_B;
    private javax.swing.JLabel C_C;
    private javax.swing.JButton btnNovaPartida;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel textFeedback;
    private javax.swing.JLabel textJogador;
    private javax.swing.JLabel textVitoriaJogador1;
    private javax.swing.JLabel textVitoriaJogador2;
    // End of variables declaration//GEN-END:variables

    private void atualizaClick(String peca) {
        switch(peca){
            case "A_A":
                this.A_A.setIcon(this.controller.getIconPeca(0, 0));
                break;
            case "B_B":
                this.B_B.setIcon(this.controller.getIconPeca(1, 1));
                break;
            case "C_C":
                this.C_C.setIcon(this.controller.getIconPeca(2, 2));
                break;
            case "A_B":
                this.A_B.setIcon(this.controller.getIconPeca(0,1));
                break;
            case "A_C":
                this.A_C.setIcon(this.controller.getIconPeca(0, 2));
                break;
            case "B_A": this.B_A.setIcon(this.controller.getIconPeca(1, 0));
                break;
            case "B_C":
                this.B_C.setIcon(this.controller.getIconPeca(1, 2));
                break;
            case "C_A":
                this.C_A.setIcon(this.controller.getIconPeca(2, 0));
                break;
            case "C_B":
                this.C_B.setIcon(this.controller.getIconPeca(2, 1));
                break;
        }
    }
}
